### ISSUE TITLE
TypeORM default connection template

### ISSUE THREAD

**Issue by flexwie** [TypedProject/tsed-cli#62]
The default connection template that is generated when using `tsed init` with typorm should use a different templating string for entities, migrations and subscribers.

Instead of 
```
"entities": ["${rootDir}/entity/**/*.ts"],  
"migrations": ["${rootDir}/migration/**/*.ts"],  
"subscribers": ["${rootDir}/subscriber/**/*.ts"]
```

it should be

```
"entities": ["${rootDir}/entity/**/*.{js,ts}"],  
"migrations": ["${rootDir}/migration/**/*.{js,ts}"],  
"subscribers": ["${rootDir}/subscriber/**/*.{js,ts}"]
```

Otherwise it will fail when running compiled in a Docker container because it can't find the entities and therefore does not have metadata for them.

**Comment by Romakita** [comment]
Hello @flexwie 
this part of template generation is handled by the typeorm CLI itself, this PR must be opened on TypeORM repository :)

See you
Romain

**Comment by Romakita** [comment]
Sorry @flexwie for my quick answer. I saw in the code, the plugin rewrite some part of the typeorm config file. 

I fix this issue :)
See you

**Comment by flexwie** [comment]
Thanks a lot for your help and this great framework!

Off topic question: I'd love to contribute, are there any beginner friendly issues or features that you could need help on?

**Comment by Romakita** [comment]
Hello @flexwie 

You can see the board here: https://github.com/orgs/TypedProject/projects/1
I'd just create a simple issue to begin contribution on CLI: 
https://github.com/TypedProject/tsed-cli/issues/67

You can review also the PR just to see how the code work for this issue ;)
https://github.com/TypedProject/tsed-cli/pull/65/commits/895157277d5c2ef9d89e52229e9f1bee7cd7039f

This is pretty simple ;). Just checkout the project and run `yarn install` (not npm because, the project use lerna and yarn workspace).

If you any problem or question, you can join me on gitter: https://gitter.im/Tsed-io/community

See you
Romain ;)
